### ISSUE TITLE
Ember source map failing

### ISSUE THREAD

**Issue by zdenal** [ef4/broccoli-uglify-sourcemap#2]
Hi guys,
last days I was struggling with failing build process with sourcemaps by `Invalid mapping` stuff. I found out, that 16 days ago new version of uglify-js was released (2.2.17). 

So I tried in package.json set version of this package exactly to previous version 2.4.16 (from `"uglify-js": "^2.4.16"` to `"uglify-js": "2.4.16"`) and everything works well again.

I don't know what is wrong with new version of uglify-js. Could you change it also in your repository till the issue with uglify-js will be solved?

**Comment by ef4** [comment]
I'm seeing successful production builds using uglify-js 2.4.19, so I think whatever was broken is fixed.
