### ISSUE TITLE
release

### ISSUE THREAD

**Issue by stefanpenner** [ef4/broccoli-uglify-sourcemap#20]
changes since last: https://github.com/ef4/broccoli-uglify-sourcemap/compare/0c1007b4b92558723c0de16d74e70a297f00d010...master

could use another set of eyes & testers or two, this appears to work as expected (but better safe the sorry)

**Comment by blimmer** [comment]
Is there an issue with when `MatchNothing` is defined and when it's used?

It's used [here](https://github.com/ef4/broccoli-uglify-sourcemap/blob/35fa040ce84a858a6116d955d1284171680eacf9/index.js#L39) but defined [here](https://github.com/ef4/broccoli-uglify-sourcemap/blob/35fa040ce84a858a6116d955d1284171680eacf9/index.js#L43-L47)

**Comment by blimmer** [comment]
I just looked over the diff and it looks sane to me.

**Comment by blimmer** [comment]
Not sure if this is related, but having this npm linked makes my production app not boot in my production environment. If I deploy the same code to my staging environment, everything works. Trying to peg the version of uglify-js without these changes to see if they're related. Just wanted to update this in case it rings any bells for you.

**Comment by stefanpenner** [comment]
> Not sure if this is related, but having this npm linked makes my production app not boot when deployed to my production environment. If I deploy the same code to my staging environment, everything works.

this is concerning, does it go away without this step?

**Comment by blimmer** [comment]
I can try deploying un-uglified and see if it works.

**Comment by stefanpenner** [comment]
> idk deployment today has been very problematic.

:S

**Comment by blimmer** [comment]
I found the bug - it's not related to this changeset. Sorry for the false alarm!!!

**Comment by stefanpenner** [comment]
If no other issues show up, i can release when i get home tonight.


@ef4 + @rwjblue feel free to release if you are good with it.

**Comment by kellyselden** [comment]
Windows errors: http://pastebin.com/hXB91p1Z

Looks like more of the common issues we've been seeing. Probably ok to ignore for now.

**Comment by stefanpenner** [comment]
```
➜  broccoli-uglify-sourcemap git:(master) npm publish
+ broccoli-uglify-sourcemap@1.1.0
```
