### ISSUE TITLE
Build failing with jquery-ui

### ISSUE THREAD

**Issue by gdub22** [ef4/broccoli-uglify-sourcemap#3]
Here is a reproduction repo: https://github.com/gdub22/sourcemap-jqueryui

Fresh ember-cli app, added jquery ui, enabled minification and sourcemaps: https://github.com/gdub22/sourcemap-jqueryui/commit/baafad281924290c9b84acf4302a77b35ef82a9f

```
Invalid mapping: {"generated":{"line":73687,"column":-50},"source":"bower_components/jquery-ui/jquery-ui.js","original":{"line":1,"column":0},"name":null}
```

Minification works fine if I disable sourcemaps.

**Comment by ef4** [comment]
If you remove ember-data, the build succeeds. I suspect this is the caused by https://github.com/emberjs/data/issues/2871

**Comment by gdub22** [comment]
Thanks for pointing me in the right direction. Building as production is working since `ember-data.prod.js` has the sourcemap comment removed.
