### ISSUE TITLE
This project appears to introduce ~1131 files via itself and its deps

### ISSUE THREAD

**Issue by stefanpenner** [ef4/broccoli-uglify-sourcemap#31]
own files mistakenly published:
---

 - [x] test      19

dependencies to investigate:
----

 - [x] broccoli-plugin     324 https://github.com/broccolijs/broccoli-plugin/issues/13
 - [ ] debug      20
 - [x] lodash     434 (often we can use merely a subset of lodash, via one of the subset modules such as lodash.uniq. we should explore that)
 - [ ] matcher-collection      35
 - [ ] mkdirp      45
 - [ ] source-map-url      12
 - [ ] symlink-or-copy      11
 - [ ] uglify-js     193
 - [ ] walk-sync      20

**Comment by kamalaknn** [comment]
Submitted #32

**Comment by stefanpenner** [comment]
@kamalaknn nice thanks!
