### ISSUE TITLE
Time based warning is not specific enough to identify source.

### ISSUE THREAD

**Issue by rwjblue** [ef4/broccoli-uglify-sourcemap#36]
[This warning](https://github.com/ef4/broccoli-uglify-sourcemap/blob/master/index.js#L131) does not give enough context to know what is actually causing the output.

Seeing the following lines in my CI logs (surrounded by a thousand lines of other things) doesn't provide enough context:

```
[WARN] `assets/web-client.js` took: 30636ms (more than 20,000ms)
[WARN] `assets/web-client.js` took: 22009ms (more than 20,000ms)
```

---

I suggest that we update the warning to at least say something like:

> [WARN] (broccoli-uglify-sourcemap) Minifying `assets/web-client.js` took: XXXXXms

Thoughts?

**Comment by ef4** [comment]
Seems good to me.

**Comment by Zooman090** [comment]
I have same problems, but with 
`[WARN] (broccoli-uglify-sourcemap) Minifying: `assets/vendor.js` took: 33105ms (more than 20,000ms)`
